### ISSUE TITLE
high quality icons

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/filetypeicons_vscode_svg#1]
@Alexey-T
using batik-rasterizer I managed to get best quality PNG icons from SVG.
no bluring, no croping, no offset, no pixelization, no noise.

```Console
java -jar batik-rasterizer-1.16.jar F:\MySSDPrograms\filetypeicons_vscode_svg -d F:\MySSDPrograms\filetypeicons_vscode_svg\out -w 64 -h 64
```

comparison SVG vs old 24 vs new 24:

https://user-images.githubusercontent.com/275333/201983223-8f2e03ed-8046-4844-85f1-3278e88191ea.mp4

here is new 16, 24, 32, 48, 64 icons.
[icons hq.zip](https://github.com/CudaText-addons/filetypeicons_vscode_svg/files/10014808/icons.hq.zip)

**Comment by Alexey-T** [comment]
great! thanks! published in addons instead the old package.

![Screenshot from 2022-11-15 20-52-12](https://user-images.githubusercontent.com/4154978/201990972-ea4953a9-98a6-4377-a694-c4fc840e7fcf.png)

**Comment by Alexey-T** [comment]
and updated Cud's default filetype icons.

**Comment by veksha** [comment]
nice! thanks for publishing. (i see typo in message box "64x46")

**Comment by Alexey-T** [comment]
fixed
